name: Telegram Bot Test

on:
  workflow_dispatch:

jobs:
  post:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - run: pip install -r requirements.txt

      - run: python bot.py
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
